### ISSUE TITLE
Option to use/switch to Icon only instead of text

### ISSUE THREAD

**Issue by msmafra** [pop-os/cosmic-workspaces-epoch#100]
I would be good for theming/"ricing" if Workspaces had an icon only mode also, instead of only text.

**Comment by git-f0x** [comment]
The workspaces button displays as an icon on larger horizontal panels, all vertical panels, and always on the dock, if that's what you're referring to.
Also, this repo is concerning the interface that opens when that button is clicked (or accessed thorough a keyboard shortcut), while the button is a part of `cosmic-applets`.
An option to configure how that applet is displayed will be added to Settings, once implemented.
