### ISSUE TITLE
Currently active wallpaper is not shown when viewing the workspaces

### ISSUE THREAD

**Issue by senntore** [pop-os/cosmic-workspaces-epoch#18]
The workspaces view only shows the default cosmic wallpaper rather than the currently active wallpaper.
Couldn't take the screenshot of it because cosmic-screenshot is not letting me do it. But you can easily reproduce it by changing the wallpaper & opening the workspaces view.

**Comment by WatchMkr** [comment]
Tracking [here](https://github.com/pop-os/cosmic-workspaces-epoch/issues/24)
