### ISSUE TITLE
Workspaces mega issue list

### ISSUE THREAD

**Issue by ryanabx** [pop-os/cosmic-workspaces-epoch#23]
- [ ] Workspaces currently runs on the dGPU, when it probably should run on the iGPU like applets and other shell components
- [ ] Missing workspace overview touchpad gesture (re: cosmic-comp)
- [ ] missing workspace overview animations
- [ ] long names and multiple windows in a workspace cause workspace previews to become skinny and tall
- [ ] currently no scrolling between workspaces in the overview (GNOME and GNOME COSMIC has this iirc)

**Comment by WatchMkr** [comment]
Thanks for listing these @ryanabx. I broke them out into individual issues for tracking.
