### ISSUE TITLE
While dragging window, dragged window appears in all workspace previews

### ISSUE THREAD

**Issue by ids1024** [pop-os/cosmic-workspaces-epoch#25]
It should probably be shown in none of them.

This will require some kind of change to the screencopy logic in cosmic-comp.

**Comment by WatchMkr** [comment]
Show in none until the mouse is over a workspace, then show the preview in the workspace.

**Comment by Drakulix** [comment]
Same btw happens with sticky-windows, perhaps they should only be shown on the active workspace?

**Comment by ids1024** [comment]
For the workspaces view, we probably would want to omit DnD surfaces from workspace screencopy for all workspaces. I guess sticky windows would make sense to include only in the active workspace.

Not sure about other potential uses of workspace capture. Probably still makes sense. Of course, with normal output capture this isn't a concern; capture is expected to include anything that shows up on the output.
