### ISSUE TITLE
Provide visual indicator when dragged window is over a drag target

### ISSUE THREAD

**Issue by ids1024** [pop-os/cosmic-workspaces-epoch#26]
Although windows can be dragged to workspaces, the behavior is a little unclear since there is no visual indication of where a window can be dragged, or that the drag will work if the mouse button is release.

The mouse cursor should change when over a workspace (behavior seemed buggy trying to implement this), and possibly other UI changes would make this clearer.

**Comment by WatchMkr** [comment]
Show the window preview in the workspace to indicate that's where the window will be when the mouse button is released.

**Comment by ids1024** [comment]
It seems like there is some Smithay bug in setting the cursor here. In either cosmic-comp or anvil, Firefox and Nautilus also show the default cursor during DnD when they should should something else.

The checks used to determine if the `SetCursor` request are valid aren't quite right in this case.

**Comment by WatchMkr** [comment]
Also show the on-hover background when the window is dragged over the preview.

![screenshot-2024-04-09-01-35-35](https://github.com/pop-os/cosmic-workspaces-epoch/assets/3430283/bd47a2a5-6222-4da9-b5fd-30bd5af4606b)

**Comment by ids1024** [comment]
It now shows the hover background. Though I'm trying to figure out why it's sometimes slow to respond when a window is dragged over a workspace. I guess some issue in iced-sctk...
