### ISSUE TITLE
Toplevel preview not shown correctly if window spawns while workspace is open

### ISSUE THREAD

**Issue by ids1024** [pop-os/cosmic-workspaces-epoch#28]
If super+t is pressed to open a terminal while the workspaces view is shown, the window is shown but has no width.

I haven't looked into exactly what the issue is (probably need to handle changing window dimensions, possibly also in cosmic-comp screencopy code).

**Comment by WatchMkr** [comment]
Close the overview when an application is launched, switched to view an applet, or an applet clicked.
