### ISSUE TITLE
Workspaces currently runs on the dGPU, when it should run on the iGPU like applets and other shell components

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-workspaces-epoch#33]

**Comment by flukejones** [comment]
This is a pretty major blocker for use on a laptop. But I'm sure y'all know that already.

I had a quick look but not really sure where one would start. If you have any pointers I'd have a go.

**Comment by ryanabx** [comment]
> This is a pretty major blocker for use on a laptop. But I'm sure y'all know that already.
> 
> I had a quick look but not really sure where one would start. If you have any pointers I'd have a go.

https://github.com/pop-os/cosmic-workspaces-epoch/blob/master/Cargo.toml#L37-L38 I think this is how the wgpu feature is enabled

cosmic-app-library, which doesn't run on the dGPU, doesn't enable wgpu by default: https://github.com/pop-os/cosmic-applibrary/blob/master/Cargo.toml#L7-L8

I'd experiment with turning off the wgpu feature and seeing if there are any problems (unique to disabling the feature, because the workspaces overview currently has lots of problems)

**Comment by ids1024** [comment]
That's part of it. It won't using the GPU for rendering at all without the `wgpu` feature.

I was just looking into this. It seems `iced_wgpu` uses `wgpu::PowerPreference::HighPerformance` when `antialiasing` is set to `true`. Not sure if it should be doing that, but the option can be disabled.

**Comment by ryanabx** [comment]
I think @wash2 may be able to provide some insight because a similar wgpu problem was happening on cosmic-applets

**Comment by Drakulix** [comment]
The applet code just sets `WGPU_POWER_PREF=low` in it's own environment. Hacky but does the job.

**Comment by ids1024** [comment]
https://github.com/pop-os/cosmic-workspaces-epoch/commit/888b1c542dca97c6298c81bb36031d331ab45ebf should have fixed this. But for some reason I can't seem to reproduce the issue on the previous commit on my gaze15. I don't see nvidia-smi listing cosmic-workspaces while it is open.

**Comment by flukejones** [comment]
If I manually start `cosmic-workspace` after starting the desktop I don't get it latching the dgpu. It's only when it is started by desktop loading that it has this issue.

Any suggestions on what to try here?

**Comment by jokeyrhyme** [comment]
@flukejones

- I've looked at the Cargo.lock for `cosmic-workspace` to see which version of libcosmic it's using: https://github.com/pop-os/cosmic-workspaces-epoch/blob/30b0cfe17b87936e08cc1e659972e8052e247d2b/Cargo.lock#L2959-L2962

- that version of libcosmic does seem to have the WGPU_POWER_PREF=low work in it: https://github.com/pop-os/libcosmic/blame/2ebf7e8e0ad522627e1dac44523695b27ea346fe/src/app/mod.rs#L152

- `cosmic-workspace` is automatically started by `cosmic-session`: https://github.com/pop-os/cosmic-session/blob/5613bc660649c65b4a4c3fb41605491b9765729a/src/main.rs#L230

- I can reproduce your finding that starting `cosmic-workspaces` later has the desirable behaviour, versus the instance of it started by `cosmic-session`

- one thing we could try is reading /proc/$PID/environ for `cosmic-workspaces` to see if it's missing the WGPU_POWER_PREF=low environment variable when it is started by `cosmic-session` and gains that variable when started later, but that would be very strange to me, and it's still very strange to me that the anti-aliasing change didn't fix this :shrug:

**Comment by ids1024** [comment]
If the behavior is different with the same env vars (and same `cosmic-workspaces` binary), maybe the compositor could be advertising something different over the `zwp_linux_dmabuf_v1` protocol at the time cosmic-session starts cosmic-workspaces, changing how Vulkan/OpenGL devices are enumerated?

Not that I'd expect anything like that. But I can't think of another thing that would be different.

**Comment by flukejones** [comment]
I just checked the pid environ for workspaces:

```
❯ ps e -ww -p 2986
    PID TTY      STAT   TIME COMMAND
   2986 tty2     Sl+    0:08 cosmic-workspaces ANDROID_NDK_ROOT=/home/luke/Android/Sdk/ndk/24.0.8215888 ANDROID_SDK_ROOT=/home/luke/Android/Sdk BAT_THEME=Monokai Extended Light CLUTTER_PAINT=disable-dynamic-max-render-time CLUTTER_VBLANK=none DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus DEBUGINFOD_URLS=https://debuginfod.fedoraproject.org/  DESKTOP_SESSION=cosmic DISPLAY=:0 EDITOR=vim GCC_COLORS=error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01 GDK_BACKEND=wayland,x11 GDMSESSION=cosmic GDM_LANG=en_NZ.UTF-8 HISTCONTROL=ignoreboth:erasedups HISTSIZE=1000 HOME=/home/luke HOSTNAME=fedora LANG=en_NZ.UTF-8 LESSOPEN=||/usr/bin/lesspipe.sh %s LOGNAME=luke LS_COLORS= MAIL=/var/spool/mail/luke MOZ_ENABLE_WAYLAND=1 PATH=/home/luke/Android/Sdk/tools/bin:/home/luke/Android/Sdk/tools:/home/luke/Android/flutter/bin:/home/luke/Android/Sdk/tools/bin:/home/luke/Android/Sdk/tools:/home/luke/Android/flutter/bin:/home/luke/.cargo/bin:/home/luke/.local/bin:/home/luke/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/luke/.local/share/JetBrains/Toolbox/scripts PWD=/home/luke QT_QPA_PLATFORM=wayland;xcb SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0 SHELL=/bin/bash SHLVL=0 STARSHIP_SESSION_KEY=1174106112865621 STARSHIP_SHELL=bash STEAM_FRAME_FORCE_CLOSE=1 USER=luke USERNAME=luke WASMER_DIR=/home/luke/.wasmer WAYLAND_DISPLAY=wayland-1 WAYLAND_SOCKET=32 XCURSOR_THEME=Cosmic XDG_CURRENT_DESKTOP=COSMIC XDG_DATA_DIRS=/home/luke/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/ XDG_RUNTIME_DIR=/run/user/1000 XDG_SEAT=seat0 XDG_SESSION_CLASS=user XDG_SESSION_DESKTOP=cosmic XDG_SESSION_ID=2 XDG_SESSION_TYPE=wayland XDG_VTNR=2 _JAVA_AWT_WM_NONREPARENTING=1
```
   
`WGPU_POWER_PREF` doesn't exist, should it?  I am starting cosmic using GDM if that is of significance here.

**Comment by ryanabx** [comment]
Here's mine, using cosmic-greeter:

```
    PID TTY      STAT   TIME COMMAND
   1759 tty1     Sl+    0:08 cosmic-workspaces DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus DEBUGINFOD_URLS=https://debuginfod.fedoraproject.org/  DISPLAY=:1 EDITOR=/usr/bin/nano GDK_BACKEND=wayland,x11 HISTCONTROL=ignoredups HISTSIZE=1000 HOME=/var/home/ryanbrue HOSTNAME=fedora LANG=en_US.UTF-8 LESSOPEN=||/usr/bin/lesspipe.sh %s LOGNAME=ryanbrue LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;37;41:su=37;41:sg=30;43:ca=00:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.avif=01;35:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.m4a=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.oga=01;36:*.opus=01;36:*.spx=01;36:*.xspf=01;36:*~=00;90:*#=00;90:*.bak=00;90:*.crdownload=00;90:*.dpkg-dist=00;90:*.dpkg-new=00;90:*.dpkg-old=00;90:*.dpkg-tmp=00;90:*.old=00;90:*.orig=00;90:*.part=00;90:*.rej=00;90:*.rpmnew=00;90:*.rpmorig=00;90:*.rpmsave=00;90:*.swp=00;90:*.tmp=00;90:*.ucf-dist=00;90:*.ucf-new=00;90:*.ucf-old=00;90: MAIL=/var/spool/mail/ryanbrue MOZ_ENABLE_WAYLAND=1 PATH=/var/home/ryanbrue/.local/bin:/var/home/ryanbrue/bin:/var/home/ryanbrue/.juliaup/bin:/var/home/ryanbrue/.cargo/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin PWD=/var/home/ryanbrue QT_QPA_PLATFORM=wayland;xcb SHELL=/bin/bash SHLVL=0 TERM=linux USER=ryanbrue WAYLAND_DISPLAY=wayland-1 WAYLAND_SOCKET=32 XCURSOR_THEME=Cosmic XDG_CURRENT_DESKTOP=COSMIC XDG_DATA_DIRS=/var/home/ryanbrue/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share XDG_RUNTIME_DIR=/run/user/1000 XDG_SEAT=seat0 XDG_SESSION_ID=2 XDG_SESSION_TYPE=wayland _JAVA_AWT_WM_NONREPARENTING=1
```

**Comment by flukejones** [comment]
@ryanabx use `strings /proc/$pid/environ`

**Comment by ryanabx** [comment]
@flukejones I don't have strings installed it seems

**Comment by mmstick** [comment]
As far as I know, libcosmic only sets WGPU_POWER_PREF for applications.

**Comment by mmstick** [comment]
Alternatively, `WGPU_ADAPTER_NAME` could be set to a substring of the active GPU's name.

**Comment by flukejones** [comment]
Here we go. After killa nd restart cosmic-workspaces:
```
❯ strings /proc/19470/environ |grep WGPU
WGPU_POWER_PREF=low
```

**Comment by ryanabx** [comment]
Maybe we need cosmic-session to set the environment variable for us?

**Comment by jokeyrhyme** [comment]
After some reading: https://www.man7.org/linux/man-pages/man5/proc.5.html

> This file contains the initial environment that was set when the currently executing program was started via [execve(2)](https://www.man7.org/linux/man-pages/man2/execve.2.html).
              
> If, after an [execve(2)](https://www.man7.org/linux/man-pages/man2/execve.2.html), the process modifies its environment (e.g., by calling functions such as [putenv(3)](https://www.man7.org/linux/man-pages/man3/putenv.3.html) or modifying the [environ(7)](https://www.man7.org/linux/man-pages/man7/environ.7.html) variable directly), this file will not reflect those changes.

So, it's probably normal to not see WGPU_POWER_PREF in /proc/$PID/environ

**Comment by ryanabx** [comment]
Not sure if I'm understanding, but fluke did see the environment variable when running cosmic-workspaces manually?

**Comment by flukejones** [comment]
@jokeyrhyme the problem is that to prevent `cosmic-workspaces` from using the dGPU, it requires `WGPU_POWER_PREF`. Which is why i am checking the initial environment.

**Comment by jokeyrhyme** [comment]
It doesn't seem as though `Command::env_clear()` ( https://doc.rust-lang.org/stable/std/process/struct.Command.html#method.env_clear ) or `Command::env_remove("WGPU_POWER_PREF")` is called anywhere in COSMIC, so every time a COSMIC process launches another process, the child is inheriting the WGPU_POWER_PREF environment variable (if the parent is using libcosmic with the "wgpu" feature), which could make verifying the provenance of the variable value a little tricky

However, I've also just noticed that `cosmic-workspaces` itself disables the "wgpu" feature in libcosmic: https://github.com/pop-os/cosmic-workspaces-epoch/blob/a014d8ca3d70f1b3b9a93b2c696db67e369c1d9c/Cargo.toml#L15

So, maybe all that is needed here is to add that to the Cargo.toml ?

**Comment by flukejones** [comment]
I ended up commenting out the `cosmic-workspaces` startup in the `cosmic-session` crate as a workaround. I've not gone any further than this as I've got other stuff I need to do unfortunately.

**Comment by WatchMkr** [comment]
Fixed
