### ISSUE TITLE
When clicking on an application to activate, toplevel doesn't activate

### ISSUE THREAD

**Issue by ryanabx** [pop-os/cosmic-workspaces-epoch#39]
https://github.com/pop-os/cosmic-workspaces-epoch/assets/56272643/7514719d-aef8-4d47-82db-e18fb203b985

**Comment by ids1024** [comment]
https://github.com/pop-os/cosmic-workspaces-epoch/commit/07f7b8f5bd1a9f66a9dd58602223ae6b0dae009d should fix this.

**Comment by ryanabx** [comment]
Thanks, I'll close this unless the issue crops up again!
