### ISSUE TITLE
Windows remain behind the overview

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-workspaces-epoch#55]
Nvidia hybrid graphics laptop on Pop 24.04. Kind of hard to describe but here's the screenshot.

![image](https://github.com/pop-os/cosmic-workspaces-epoch/assets/3430283/144a3417-c5cf-460c-a752-55eb1e478c1f)

**Comment by ids1024** [comment]
Looks like for some reason cosmic-workspaces isn't drawing the background. So it's just transparent, over the window that is open.

**Comment by WatchMkr** [comment]
This is not happening as of this morning. Closing and will reopen if it appears again.
