### ISSUE TITLE
Windows in workspaces view lose their transparency

### ISSUE THREAD

**Issue by Kartonrealista** [pop-os/cosmic-workspaces-epoch#63]
If you use a Cosmic theme with some element (background, container, etc.) having alpha < 1, or have set "background opacity" in cosmic-term settings below 100%, when in workspaces view those windows become opaque.

![image](https://github.com/user-attachments/assets/09ee5ba4-f2ce-45b0-a1e1-ec6de2f6255c)
![image](https://github.com/user-attachments/assets/39f5d26e-2424-415e-8409-8c9fe78974e0)

**Comment by WatchMkr** [comment]
This is now fixed.
