### ISSUE TITLE
Workspaces previews not showing on second display

### ISSUE THREAD

**Issue by curiouslad** [pop-os/cosmic-workspaces-epoch#68]
There are workspaces previews shown on laptop display, but on monitor display there is no previews in workspaces overview 
![screenshot-2024-07-20-05-25-51](https://github.com/user-attachments/assets/86c36d05-6a5f-4654-a587-97b5b55362a4)

**Comment by msmafra** [comment]
It shows only on my laptops screen, but not on my external monitor. Doesn't matter if is set to independant workspaces or to extend workspaces to both monitors

![screenshot-2024-07-20-14-32-04](https://github.com/user-attachments/assets/98b0b996-1f12-43d2-87bf-6e059615532f)
![screenshot-2024-07-20-14-27-15](https://github.com/user-attachments/assets/6adc85b2-b330-4285-a35b-9a2208a839b7)
