### ISSUE TITLE
Workspace switching animation cancelling

### ISSUE THREAD

**Issue by iciclejj** [pop-os/cosmic-workspaces-epoch#77]
This only happens when switching from the 2nd to the 1st (top-most/left-most) workspace.

If I press the hotkey to switch towards a lower-numbered workspace (ctrl+super+up/left), and then re-press the hotkey before the animation has finished, it restarts the animation. This can be repeated indefinitely.

For example, if you're at workspace 4 and rapidly spam the hotkey to move closer to workspace 1 until you reach it, you will successfully switch all the way to workspace 2, but then be indefinitely stuck at repeatedly switching from workspace 2 to workspace 1 until you stop spamming the hotkey. When you stop you do end up at workspace 1.

**Comment by bsutherland333** [comment]
I found this also occurs for transitions between any workspaces when using the number keys rather than up/down to navigate workspaces.

**Comment by bsutherland333** [comment]
I this issue has since been fixed for me.

**Comment by iciclejj** [comment]
Fixed for me too, I'll close this.
