### ISSUE TITLE
Workspace previews are blank/flickery

### ISSUE THREAD

**Issue by git-f0x** [pop-os/cosmic-workspaces-epoch#80]
Window previews are also occasionally incomplete.
Was present in 22.04, but is also present on 24.04. Started happening after one of the mid-July commits (maybe 2de366939bc4bd475c36ff805fb96272f207bb74).
Also, applet popups don't close on click while in the overview.

https://github.com/user-attachments/assets/de1d52a2-d521-4923-a10a-cfe256d51d91

On AMD graphics (RX 570), though there's also an Intel iGPU.

**Comment by BrodieRobertson** [comment]
I have seen this behavior in a virtual machine, but not running on hardware with an AMD 6750XT

**Comment by git-f0x** [comment]
Do you have an iGPU? Maybe that triggers it on hardware.

**Comment by iamkartiknayak** [comment]
It happens occasionally, but only on external displays.

**Comment by rawkode** [comment]
Same behaviour here, on bare metal.

AMD Radeon RX 7900 XT

**Comment by git-f0x** [comment]
This appears to be fixed on my end with pop-os/cosmic-comp#780 (though the fix mentions software rendering). I'll close this if others confirm the same.

**Comment by iamkartiknayak** [comment]
Thr issue still persist

**Comment by git-f0x** [comment]
That seems more related to #61, than to the previews themselves being blank/flickery.

**Comment by iamkartiknayak** [comment]
On my main display workspace switcher worked fine even  when it first got released.

**Comment by git-f0x** [comment]
I'll close this, since I haven't been able to reproduce the issue in a while.

**Comment by iamkartiknayak** [comment]
The issue still exist for external display. It shows a rectangle with no preview

![Screenshot_2024-09-26_03-22-58](https://github.com/user-attachments/assets/0c28bf3b-9465-4059-bef7-023f6aa147d4)

![Screenshot_2024-09-26_03-27-11](https://github.com/user-attachments/assets/496915b3-7973-4d19-8005-48f4043075f6)

**Comment by git-f0x** [comment]
That is unrelated to this and seems more similar to #45, #61 or #68.
